"""initial_schema

Revision ID: 84af2f388529
Revises: 
Create Date: 2026-07-19 00:56:24.776431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84af2f388529'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('audit_logs', 'admin_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_time', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.alter_column('coupon_redemptions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('coupon_redemptions', 'coupon_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('coupon_redemptions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_coupon_redemptions_id'), table_name='coupon_redemptions')
    op.create_index(op.f('ix_coupon_redemptions_coupon_id'), 'coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index('ix_coupon_redemptions_user_coupon', 'coupon_redemptions', ['user_id', 'coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_user_id'), 'coupon_redemptions', ['user_id'], unique=False)
    op.add_column('coupons', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('coupons', sa.Column('usage_limit', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('redeemed_count', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('coupons', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('coupons', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_column('coupons', 'discount_value')
    op.drop_column('coupons', 'min_cart_value')
    op.drop_column('coupons', 'type')
    op.alter_column('dominos_otp_requests', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_dominos_otp_requests_id'), table_name='dominos_otp_requests')
    op.create_index(op.f('ix_dominos_otp_requests_mobile_number'), 'dominos_otp_requests', ['mobile_number'], unique=False)
    op.add_column('dominos_sessions', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('dominos_sessions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('dominos_sessions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('dominos_sessions', 'mobile_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('dominos_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('dominos_sessions', 'admin_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('dominos_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_dominos_sessions_id'), table_name='dominos_sessions')
    op.create_index('ix_dominos_sessions_expires', 'dominos_sessions', ['expires_at'], unique=False)
    op.create_index('ix_dominos_sessions_mobile_active', 'dominos_sessions', ['mobile_number', 'is_active'], unique=False)
    op.create_index(op.f('ix_dominos_sessions_mobile_number'), 'dominos_sessions', ['mobile_number'], unique=False)
    op.alter_column('error_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_error_logs_id'), table_name='error_logs')
    op.create_index(op.f('ix_error_logs_type'), 'error_logs', ['type'], unique=False)
    op.add_column('gift_cards', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('gift_cards', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('gift_cards', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('gift_cards', 'used_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index(op.f('ix_gift_cards_id'), table_name='gift_cards')
    op.drop_column('gift_cards', 'uploaded_at')
    op.alter_column('location_pricing', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_location_pricing_id'), table_name='location_pricing')
    op.drop_column('location_pricing', 'created_at')
    op.drop_column('location_pricing', 'updated_at')
    op.alter_column('login_attempts', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.create_index('ix_login_attempts_user_time', 'login_attempts', ['username', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('notifications', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order_items', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order_notes', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_notes_id'), table_name='order_notes')
    op.create_index(op.f('ix_order_notes_order_id'), 'order_notes', ['order_id'], unique=False)
    op.drop_constraint(None, 'order_notes', type_='foreignkey')
    op.create_foreign_key(None, 'order_notes', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order_status_history', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'order_status_history', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'gift_card_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_time', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index(op.f('ix_products_availability'), 'products', ['availability'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_category_avail', 'products', ['category', 'availability'], unique=False)
    op.create_index('ix_products_sort', 'products', ['sort_order'], unique=False)
    op.add_column('proxies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('proxies', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('proxies', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_proxies_id'), table_name='proxies')
    op.alter_column('proxy_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('proxy_logs', 'proxy_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_proxy_logs_id'), table_name='proxy_logs')
    op.create_index(op.f('ix_proxy_logs_proxy_id'), 'proxy_logs', ['proxy_id'], unique=False)
    op.alter_column('qr_generation_history', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('qr_generation_history', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index(op.f('ix_qr_generation_history_id'), table_name='qr_generation_history')
    op.alter_column('rider_assignments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_rider_assignments_id'), table_name='rider_assignments')
    op.drop_constraint(None, 'rider_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'rider_assignments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('robot_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('robot_logs', 'session_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index(op.f('ix_robot_logs_id'), table_name='robot_logs')
    op.create_index(op.f('ix_robot_logs_session_id'), 'robot_logs', ['session_id'], unique=False)
    op.create_index('ix_robot_logs_session_stage', 'robot_logs', ['session_id', 'stage'], unique=False)
    op.add_column('saved_addresses', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('saved_addresses', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('saved_addresses', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('saved_addresses', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_saved_addresses_id'), table_name='saved_addresses')
    op.create_index(op.f('ix_saved_addresses_user_id'), 'saved_addresses', ['user_id'], unique=False)
    op.drop_constraint(None, 'saved_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'saved_addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('sessions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('sessions', 'last_active',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.create_index('ix_sessions_last_active', 'sessions', ['last_active'], unique=False)
    op.create_index('ix_sessions_user_active', 'sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('support_messages', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('support_messages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('support_messages', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('support_messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_support_messages_id'), table_name='support_messages')
    op.create_index(op.f('ix_support_messages_user_id'), 'support_messages', ['user_id'], unique=False)
    op.create_index('ix_support_user_unread', 'support_messages', ['user_id', 'is_read'], unique=False)
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.add_column('users', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_role_created', 'users', ['role', 'created_at'], unique=False)
    op.create_index('ix_users_wallet', 'users', ['wallet_balance'], unique=False)
    op.alter_column('utr_attempts', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_utr_attempts_id'), table_name='utr_attempts')
    op.drop_index(op.f('ix_verified_utrs_utr'), table_name='verified_utrs')
    op.create_index(op.f('ix_verified_utrs_order_id'), 'verified_utrs', ['order_id'], unique=False)
    op.add_column('wallet_transactions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('wallet_transactions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('wallet_transactions', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('wallet_transactions', 'updated_at')
    op.drop_index(op.f('ix_verified_utrs_order_id'), table_name='verified_utrs')
    op.create_index(op.f('ix_verified_utrs_utr'), 'verified_utrs', ['utr'], unique=False)
    op.create_index(op.f('ix_utr_attempts_id'), 'utr_attempts', ['id'], unique=False)
    op.alter_column('utr_attempts', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index('ix_users_wallet', table_name='users')
    op.drop_index('ix_users_role_created', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'version')
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=False)
    op.drop_index('ix_support_user_unread', table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_user_id'), table_name='support_messages')
    op.create_index(op.f('ix_support_messages_id'), 'support_messages', ['id'], unique=False)
    op.alter_column('support_messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('support_messages', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('support_messages', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('support_messages', 'updated_at')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_active', table_name='sessions')
    op.drop_index('ix_sessions_last_active', table_name='sessions')
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sessions', 'last_active',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('sessions', 'updated_at')
    op.drop_constraint(None, 'saved_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'saved_addresses', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_saved_addresses_user_id'), table_name='saved_addresses')
    op.create_index(op.f('ix_saved_addresses_id'), 'saved_addresses', ['id'], unique=False)
    op.alter_column('saved_addresses', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('saved_addresses', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('saved_addresses', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('saved_addresses', 'updated_at')
    op.drop_index('ix_robot_logs_session_stage', table_name='robot_logs')
    op.drop_index(op.f('ix_robot_logs_session_id'), table_name='robot_logs')
    op.create_index(op.f('ix_robot_logs_id'), 'robot_logs', ['id'], unique=False)
    op.alter_column('robot_logs', 'session_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('robot_logs', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'rider_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'rider_assignments', 'orders', ['order_id'], ['id'])
    op.create_index(op.f('ix_rider_assignments_id'), 'rider_assignments', ['id'], unique=False)
    op.alter_column('rider_assignments', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_qr_generation_history_id'), 'qr_generation_history', ['id'], unique=False)
    op.alter_column('qr_generation_history', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('qr_generation_history', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_proxy_logs_proxy_id'), table_name='proxy_logs')
    op.create_index(op.f('ix_proxy_logs_id'), 'proxy_logs', ['id'], unique=False)
    op.alter_column('proxy_logs', 'proxy_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('proxy_logs', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_proxies_id'), 'proxies', ['id'], unique=False)
    op.alter_column('proxies', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('proxies', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('proxies', 'updated_at')
    op.drop_index('ix_products_sort', table_name='products')
    op.drop_index('ix_products_category_avail', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_availability'), table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('products', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('products', 'updated_at')
    op.drop_index('ix_orders_user_status', table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index('ix_orders_status_time', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'gift_card_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orders', 'version')
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'order_status_history', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.alter_column('order_status_history', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'order_notes', type_='foreignkey')
    op.create_foreign_key(None, 'order_notes', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('ix_order_notes_order_id'), table_name='order_notes')
    op.create_index(op.f('ix_order_notes_id'), 'order_notes', ['id'], unique=False)
    op.alter_column('order_notes', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('order_items', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('notifications', 'updated_at')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index('ix_login_attempts_user_time', table_name='login_attempts')
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.alter_column('login_attempts', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('location_pricing', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('location_pricing', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.create_index(op.f('ix_location_pricing_id'), 'location_pricing', ['id'], unique=False)
    op.alter_column('location_pricing', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('gift_cards', sa.Column('uploaded_at', sa.DATETIME(), nullable=True))
    op.create_index(op.f('ix_gift_cards_id'), 'gift_cards', ['id'], unique=False)
    op.alter_column('gift_cards', 'used_by_user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('gift_cards', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('gift_cards', 'updated_at')
    op.drop_column('gift_cards', 'created_at')
    op.drop_index(op.f('ix_error_logs_type'), table_name='error_logs')
    op.create_index(op.f('ix_error_logs_id'), 'error_logs', ['id'], unique=False)
    op.alter_column('error_logs', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_dominos_sessions_mobile_number'), table_name='dominos_sessions')
    op.drop_index('ix_dominos_sessions_mobile_active', table_name='dominos_sessions')
    op.drop_index('ix_dominos_sessions_expires', table_name='dominos_sessions')
    op.create_index(op.f('ix_dominos_sessions_id'), 'dominos_sessions', ['id'], unique=False)
    op.alter_column('dominos_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('dominos_sessions', 'admin_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('dominos_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('dominos_sessions', 'mobile_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dominos_sessions', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('dominos_sessions', 'updated_at')
    op.drop_column('dominos_sessions', 'version')
    op.drop_index(op.f('ix_dominos_otp_requests_mobile_number'), table_name='dominos_otp_requests')
    op.create_index(op.f('ix_dominos_otp_requests_id'), 'dominos_otp_requests', ['id'], unique=False)
    op.alter_column('dominos_otp_requests', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('coupons', sa.Column('type', sa.VARCHAR(), nullable=True))
    op.add_column('coupons', sa.Column('min_cart_value', sa.FLOAT(), nullable=True))
    op.add_column('coupons', sa.Column('discount_value', sa.FLOAT(), nullable=True))
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.alter_column('coupons', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('coupons', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('coupons', 'updated_at')
    op.drop_column('coupons', 'redeemed_count')
    op.drop_column('coupons', 'usage_limit')
    op.drop_column('coupons', 'value')
    op.drop_index(op.f('ix_coupon_redemptions_user_id'), table_name='coupon_redemptions')
    op.drop_index('ix_coupon_redemptions_user_coupon', table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_coupon_id'), table_name='coupon_redemptions')
    op.create_index(op.f('ix_coupon_redemptions_id'), 'coupon_redemptions', ['id'], unique=False)
    op.alter_column('coupon_redemptions', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('coupon_redemptions', 'coupon_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('coupon_redemptions', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('audit_logs', 'admin_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
